### ISSUE TITLE
Bulk creating Deep Linking URLs not preserving the order

### ISSUE THREAD

**Issue by krishnakumarcitrus** [BranchMetrics/branch-deep-linking-public-api#21]
When multiple branch links are created , the order of URL's in response is changed.
So, we are unable to identify for which item the URL belongs.
Or if at least some other request parameters other than URL was returned back, we could identify the URL.
Or is there any other work around for this?

Thanks.

**Comment by ahmednawar** [comment]
@krishnakumarcitrus I was unable to reproduce. Do you have a curl I could use to test?
